# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumBrazeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumBrazeExample
  pod "TealiumBraze", "~> 0.0.7"
  pod 'tealium-swift/TealiumLogger'
  pod 'tealium-swift/TealiumAppData'
  pod 'tealium-swift/TealiumDeviceData'
  pod 'tealium-swift/TealiumLifecycle'

end
