# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TealiumBrazeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumBrazeExample
  pod "TealiumBraze", :path=> "../"
   pod "tealium-swift/Lifecycle", :git => 'https://github.com/Tealium/tealium-swift.git', :branch => 'mt-1115'
   pod "tealium-swift/RemoteCommands", :git => 'https://github.com/Tealium/tealium-swift.git', :branch => 'mt-1115'
end
