# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'TealiumBrazeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TealiumBrazeExample
	pod "tealium-swift", "~> 1.7.0"
	pod "Appboy-iOS-SDK", "<= 3.15.0"
end
